#define SSETBIT(WORD, BIT) WORD=(1<<BIT)
#define SCLRBIT(WORD, BIT) WORD=(1<<BIT)

#define SETBIT(WORD, BIT) WORD|=(1<<BIT)
#define CLRBIT(WORD, BIT) WORD&=~(1<<BIT)
#define CPLBIT(WORD, BIT) WORD^=(1<<BIT)

#define READBIT(WORD, BIT) ((WORD>>BIT)&1)
#define WRITEBIT(WORD, BIT, DATA) WORD=((WORD&~(1<<BIT))|((DATA&1)<<BIT))

#define READWRITEBIT1(WORD, DBIT, SBIT) WORD=((WORD&~(1<<DBIT))|(((WORD>>SBIT)&1)<<DBIT))
#define READWRITEBIT2(DWORD, DBIT, SWORD, SBIT) DWORD=((DWORD&~(1<<DBIT))|(((SWORD>>SBIT)&1)<<DBIT))

#define SWAPBIT(WORD, BIT1, BIT2) WORD=((WORD&~((1<<BIT1)|(1<<BIT2)))|(((WORD>>BIT1)&1)<<BIT2)|(((WORD>>BIT2)&1)<<BIT1))

#define READNIBBLE(WORD, BIT) ((WORD>>BIT)&15)
#define WRITENIBBLE(WORD, BIT, DATA) WORD=((WORD&~(15<<BIT))|((DATA&15)<<BIT))

#define READBYTE(WORD, BIT) ((WORD>>BIT)&255)
#define WRITEBYTE(WORD, BIT, DATA) WORD=((WORD&~(255<<BIT))|((DATA&255)<<BIT))

#define FUN1 0 // 00 -> GPIO
#define FUN2 1 // 01 -> ALT 1
#define FUN3 2 // 10 -> ALT 2
#define FUN4 3 // 11 -> ALT 3
#define CFGPIN(WORD, PIN, FUNC) WORD=((PIN<16)?((WORD&~(3<<(PIN*2)))|(FUNC<<(PIN*2))):((WORD&~(3<<((PIN-16)*2)))|(FUNC<<((PIN-16)*2))))
